version: "3.8"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloudpass
    volumes:
      - /home/isaac/nextcloud/config:/config
      - /home/isaac/nextcloud/data:/data
    ports:
      - 1234:443
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nextcloud-db
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloudpass
    volumes:
      - /home/isaac/nextcloud/db:/var/lib/postgresql/data
    restart: unless-stopped
